[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "debuginfo=0", "-C", "strip=debuginfo"]

[target.x86_64-unknown-linux-gnu-znver3]
rustflags = [
    "-C",
    "strip=debuginfo",
    "-C",
    "target-cpu=znver3",
    "-C",
    "relro-level=full",
    "-Z",
    "tune-cpu=znver3",
]
